int gcd(int , int );
int FastExponention(int , int , int* , int* );
int FindT(int a, int m, int n);
int PrimarityTest(int a, int i);
int inverse(int a, int b);
int register_user(char* , char* ,char*);
int login_user(char* ,char* ,char* ,char* ,int ,int ,int);
int read_file();
int inbox(char* , char* , char* );
int KeyGeneration();
int Encryption(int , FILE* );
int Decryption(int , FILE* );